# left:reya 1-4, right: reya 5-8
robot_left_sites = {
    '模具腔数-设置': {'Name': '模具腔数-设置', 'DataType': 'Int', 'Address': 'DB511.DBW0'},
    '工作位-设置': {'Name': '工作位-设置', 'DataType': 'Int', 'Address': 'DB511.DBW2'},
    'Main_X1-设置': {'Name': 'Main_X1-设置', 'DataType': 'Real', 'Address': 'DB511.DBD4'},
    'Main_Y1-设置': {'Name': 'Main_Y1-设置', 'DataType': 'Real', 'Address': 'DB511.DBD8'},
    'Main_X2-设置': {'Name': 'Main_X2-设置', 'DataType': 'Real', 'Address': 'DB511.DBD12'},
    'Main_Y2-设置': {'Name': 'Main_Y2-设置', 'DataType': 'Real', 'Address': 'DB511.DBD16'},
    'Main_X3-设置': {'Name': 'Main_X3-设置', 'DataType': 'Real', 'Address': 'DB511.DBD20'},
    'Main_Y3-设置': {'Name': 'Main_Y3-设置', 'DataType': 'Real', 'Address': 'DB511.DBD24'},
    'Main_X4-设置': {'Name': 'Main_X4-设置', 'DataType': 'Real', 'Address': 'DB511.DBD28'},
    'Main_Y4-设置': {'Name': 'Main_Y4-设置', 'DataType': 'Real', 'Address': 'DB511.DBD32'},
    'Main_X5-设置': {'Name': 'Main_X5-设置', 'DataType': 'Real', 'Address': 'DB511.DBD36'},
    'Main_Y5-设置': {'Name': 'Main_Y5-设置', 'DataType': 'Real', 'Address': 'DB511.DBD40'},
    'Main_X6-设置': {'Name': 'Main_X6-设置', 'DataType': 'Real', 'Address': 'DB511.DBD44'},
    'Main_Y6-设置': {'Name': 'Main_Y6-设置', 'DataType': 'Real', 'Address': 'DB511.DBD48'},
    'Assist_X1-设置': {'Name': 'Assist_X1-设置', 'DataType': 'Real', 'Address': 'DB511.DBD52'},
    'Assist_Y1-设置': {'Name': 'Assist_Y1-设置', 'DataType': 'Real', 'Address': 'DB511.DBD56'},
    'Assist_X2-设置': {'Name': 'Assist_X2-设置', 'DataType': 'Real', 'Address': 'DB511.DBD60'},
    'Assist_Y2-设置': {'Name': 'Assist_Y2-设置', 'DataType': 'Real', 'Address': 'DB511.DBD64'},
    'Assist_X3-设置': {'Name': 'Assist_X3-设置', 'DataType': 'Real', 'Address': 'DB511.DBD68'},
    'Assist_Y3-设置': {'Name': 'Assist_Y3-设置', 'DataType': 'Real', 'Address': 'DB511.DBD72'},
    'Assist_X4-设置': {'Name': 'Assist_X4-设置', 'DataType': 'Real', 'Address': 'DB511.DBD76'},
    'Assist_Y4-设置': {'Name': 'Assist_Y4-设置', 'DataType': 'Real', 'Address': 'DB511.DBD80'},
    'Assist_X5-设置': {'Name': 'Assist_X5-设置', 'DataType': 'Real', 'Address': 'DB511.DBD84'},
    'Assist_Y5-设置': {'Name': 'Assist_Y5-设置', 'DataType': 'Real', 'Address': 'DB511.DBD88'},
    'Main_Speed-设置': {'Name': 'Main_Speed-设置', 'DataType': 'Real', 'Address': 'DB511.DBD92'},
    'Ass_Speed-设置': {'Name': 'Ass_Speed-设置', 'DataType': 'Real', 'Address': 'DB511.DBD96'},
    'Middle_Y1-设置': {'Name': 'Middle_Y1-设置', 'DataType': 'Real', 'Address': 'DB511.DBD100'},
    'Up_Y1-设置': {'Name': 'Up_Y1-设置', 'DataType': 'Real', 'Address': 'DB511.DBD104'},
    'H1-设置': {'Name': 'H1-设置', 'DataType': 'Real', 'Address': 'DB511.DBD108'},
    'Middle_Y2-设置': {'Name': 'Middle_Y2-设置', 'DataType': 'Real', 'Address': 'DB511.DBD112'},
    'Up_Y2-设置': {'Name': 'Up_Y2-设置', 'DataType': 'Real', 'Address': 'DB511.DBD116'},
    'H2-设置': {'Name': 'H2-设置', 'DataType': 'Real', 'Address': 'DB511.DBD120'},
    'Middle_Y3-设置': {'Name': 'Middle_Y3-设置', 'DataType': 'Real', 'Address': 'DB511.DBD124'},
    'Up_Y3-设置': {'Name': 'Up_Y3-设置', 'DataType': 'Real', 'Address': 'DB511.DBD128'},
    'H3-设置': {'Name': 'H3-设置', 'DataType': 'Real', 'Address': 'DB511.DBD132'},
    'Middle_Y4-设置': {'Name': 'Middle_Y4-设置', 'DataType': 'Real', 'Address': 'DB511.DBD136'},
    'Up_Y4-设置': {'Name': 'Up_Y4-设置', 'DataType': 'Real', 'Address': 'DB511.DBD140'},
    'H4-设置': {'Name': 'H4-设置', 'DataType': 'Real', 'Address': 'DB511.DBD144'},
    'order-设置': {'Name': 'order-设置', 'DataType': 'Int', 'Address': 'DB511.DBW148'},
    '模具类型-设置': {'Name': '模具类型-设置', 'DataType': 'Real', 'Address': 'DB511.DBD150'},
    '启动-设置': {'Name': '启动-设置', 'DataType': 'Int', 'Address': 'DB511.DBW268'},
    '申请参数-设置': {'Name': '申请参数-设置', 'DataType': 'Int', 'Address': 'DB511.DBW270'},
    'spare44-设置': {'Name': 'spare44-设置', 'DataType': 'Int', 'Address': 'DB511.DBW272'}}

robot_right_sites = {
    '模具腔数-设置': {'Name': '模具腔数-设置', 'DataType': 'Int', 'Address': 'DB511.DBW274'},
    '工作位-设置': {'Name': '工作位-设置', 'DataType': 'Int', 'Address': 'DB511.DBW276'},
    'Main_X1-设置': {'Name': 'Main_X1-设置', 'DataType': 'Real', 'Address': 'DB511.DBD278'},
    'Main_Y1-设置': {'Name': 'Main_Y1-设置', 'DataType': 'Real', 'Address': 'DB511.DBD282'},
    'Main_X2-设置': {'Name': 'Main_X2-设置', 'DataType': 'Real', 'Address': 'DB511.DBD286'},
    'Main_Y2-设置': {'Name': 'Main_Y2-设置', 'DataType': 'Real', 'Address': 'DB511.DBD290'},
    'Main_X3-设置': {'Name': 'Main_X3-设置', 'DataType': 'Real', 'Address': 'DB511.DBD294'},
    'Main_Y3-设置': {'Name': 'Main_Y3-设置', 'DataType': 'Real', 'Address': 'DB511.DBD298'},
    'Main_X4-设置': {'Name': 'Main_X4-设置', 'DataType': 'Real', 'Address': 'DB511.DBD302'},
    'Main_Y4-设置': {'Name': 'Main_Y4-设置', 'DataType': 'Real', 'Address': 'DB511.DBD306'},
    'Main_X5-设置': {'Name': 'Main_X5-设置', 'DataType': 'Real', 'Address': 'DB511.DBD310'},
    'Main_Y5-设置': {'Name': 'Main_Y5-设置', 'DataType': 'Real', 'Address': 'DB511.DBD314'},
    'Main_X6-设置': {'Name': 'Main_X6-设置', 'DataType': 'Real', 'Address': 'DB511.DBD318'},
    'Main_Y6-设置': {'Name': 'Main_Y6-设置', 'DataType': 'Real', 'Address': 'DB511.DBD322'},
    'Assist_X1-设置': {'Name': 'Assist_X1-设置', 'DataType': 'Real', 'Address': 'DB511.DBD326'},
    'Assist_Y1-设置': {'Name': 'Assist_Y1-设置', 'DataType': 'Real', 'Address': 'DB511.DBD330'},
    'Assist_X2-设置': {'Name': 'Assist_X2-设置', 'DataType': 'Real', 'Address': 'DB511.DBD334'},
    'Assist_Y2-设置': {'Name': 'Assist_Y2-设置', 'DataType': 'Real', 'Address': 'DB511.DBD338'},
    'Assist_X3-设置': {'Name': 'Assist_X3-设置', 'DataType': 'Real', 'Address': 'DB511.DBD342'},
    'Assist_Y3-设置': {'Name': 'Assist_Y3-设置', 'DataType': 'Real', 'Address': 'DB511.DBD346'},
    'Assist_X4-设置': {'Name': 'Assist_X4-设置', 'DataType': 'Real', 'Address': 'DB511.DBD350'},
    'Assist_Y4-设置': {'Name': 'Assist_Y4-设置', 'DataType': 'Real', 'Address': 'DB511.DBD354'},
    'Assist_X5-设置': {'Name': 'Assist_X5-设置', 'DataType': 'Real', 'Address': 'DB511.DBD358'},
    'Assist_Y5-设置': {'Name': 'Assist_Y5-设置', 'DataType': 'Real', 'Address': 'DB511.DBD362'},
    'Main_Speed-设置': {'Name': 'Main_Speed-设置', 'DataType': 'Real', 'Address': 'DB511.DBD366'},
    'Ass_Speed-设置': {'Name': 'Ass_Speed-设置', 'DataType': 'Real', 'Address': 'DB511.DBD370'},
    'Middle_Y1-设置': {'Name': 'Middle_Y1-设置', 'DataType': 'Real', 'Address': 'DB511.DBD374'},
    'Up_Y1-设置': {'Name': 'Up_Y1-设置', 'DataType': 'Real', 'Address': 'DB511.DBD378'},
    'H1-设置': {'Name': 'H1-设置', 'DataType': 'Real', 'Address': 'DB511.DBD382'},
    'Middle_Y2-设置': {'Name': 'Middle_Y2-设置', 'DataType': 'Real', 'Address': 'DB511.DBD386'},
    'Up_Y2-设置': {'Name': 'Up_Y2-设置', 'DataType': 'Real', 'Address': 'DB511.DBD390'},
    'H2-设置': {'Name': 'H2-设置', 'DataType': 'Real', 'Address': 'DB511.DBD394'},
    'Middle_Y3-设置': {'Name': 'Middle_Y3-设置', 'DataType': 'Real', 'Address': 'DB511.DBD398'},
    'Up_Y3-设置': {'Name': 'Up_Y3-设置', 'DataType': 'Real', 'Address': 'DB511.DBD402'},
    'H3-设置': {'Name': 'H3-设置', 'DataType': 'Real', 'Address': 'DB511.DBD406'},
    'Middle_Y4-设置': {'Name': 'Middle_Y4-设置', 'DataType': 'Real', 'Address': 'DB511.DBD410'},
    'Up_Y4-设置': {'Name': 'Up_Y4-设置', 'DataType': 'Real', 'Address': 'DB511.DBD414'},
    'H4-设置': {'Name': 'H4-设置', 'DataType': 'Real', 'Address': 'DB511.DBD418'},
    'order-设置': {'Name': 'order-设置', 'DataType': 'Int', 'Address': 'DB511.DBW422'},
    '模具类型-设置': {'Name': '模具类型-设置', 'DataType': 'Real', 'Address': 'DB511.DBD424'},
    '启动-设置': {'Name': '启动-设置', 'DataType': 'Int', 'Address': 'DB511.DBW542'},
    '申请参数-设置': {'Name': '申请参数-设置', 'DataType': 'Int', 'Address': 'DB511.DBW544'},
    'spare44-设置': {'Name': 'spare44-设置', 'DataType': 'Int', 'Address': 'DB511.DBW546'}}

robot_left_status_read_sites = {
    '启动状态-实时': {'Name': '启动状态-实时', 'DataType': 'bool', 'Address': 'DB500.DBX0.0'},
    '自动状态-实时': {'Name': '自动状态-实时', 'DataType': 'bool', 'Address': 'DB500.DBX0.1'},
    '半自动状态-实时': {'Name': '半自动状态-实时', 'DataType': 'bool', 'Address': 'DB500.DBX0.2'},
    '手动状态-实时': {'Name': '手动状态-实时', 'DataType': 'bool', 'Address': 'DB500.DBX0.3'},
    '复位状态-实时': {'Name': '复位状态-实时', 'DataType': 'bool', 'Address': 'DB500.DBX0.4'},
    '急停状态-实时': {'Name': '急停状态-实时', 'DataType': 'bool', 'Address': 'DB500.DBX0.6'},
    '备用-实时': {'Name': '备用-实时', 'DataType': 'bool', 'Address': 'DB500.DBX0.7'}}

# todo 点位对照不对，需要再问滕工
robot_right_status_read_sites = {
    '启动状态-实时': {'Name': '启动状态-实时', 'DataType': 'bool', 'Address': 'DB5033.DBX22.0'},
    '自动状态-实时': {'Name': '自动状态-实时', 'DataType': 'bool', 'Address': 'DB5033.DBX22.1'},
    '半自动状态-实时': {'Name': '半自动状态-实时', 'DataType': 'bool', 'Address': 'DB5033.DBX22.2'},
    '手动状态-实时': {'Name': '手动状态-实时', 'DataType': 'bool', 'Address': 'DB5033.DBX22.3'},
    '复位状态-实时': {'Name': '复位状态-实时', 'DataType': 'bool', 'Address': 'DB5033.DBX22.4'},
    '急停状态-实时': {'Name': '急停状态-实时', 'DataType': 'bool', 'Address': 'DB5033.DBX22.6'},
    '备用-实时': {'Name': '备用-实时', 'DataType': 'bool', 'Address': 'DB5033.DBX22.7'}}

robot_status_write_left_sites = {
    '弃料按钮-设置': {'Name': '弃料按钮-设置', 'DataType': 'bool', 'Address': 'DB503.DBX22.0'},
    '手动按钮-设置': {'Name': '手动按钮-设置', 'DataType': 'bool', 'Address': 'DB503.DBX22.1'},
    '自动按钮-设置': {'Name': '自动按钮-设置', 'DataType': 'bool', 'Address': 'DB503.DBX22.2'},
    '半自动按钮-设置': {'Name': '半自动按钮-设置', 'DataType': 'bool', 'Address': 'DB503.DBX22.3'},
    '启动按钮-设置': {'Name': '启动按钮-设置', 'DataType': 'bool', 'Address': 'DB503.DBX22.4'},
    '复位按钮-设置': {'Name': '复位按钮-设置', 'DataType': 'bool', 'Address': 'DB503.DBX22.5'},
    '急停按钮-设置': {'Name': '急停按钮-设置', 'DataType': 'bool', 'Address': 'DB503.DBX22.6'},
    '备用-设置': {'Name': '备用-设置', 'DataType': 'bool', 'Address': 'DB503.DBX22.7'}}

robot_status_write_right_sites = {
    '弃料按钮-设置': {'Name': '弃料按钮-设置', 'DataType': 'bool', 'Address': 'DB5033.DBX22.0'},
    '手动按钮-设置': {'Name': '手动按钮-设置', 'DataType': 'bool', 'Address': 'DB5033.DBX22.1'},
    '自动按钮-设置': {'Name': '自动按钮-设置', 'DataType': 'bool', 'Address': 'DB5033.DBX22.2'},
    '半自动按钮-设置': {'Name': '半自动按钮-设置', 'DataType': 'bool', 'Address': 'DB5033.DBX22.3'},
    '启动按钮-设置': {'Name': '启动按钮-设置', 'DataType': 'bool', 'Address': 'DB5033.DBX22.4'},
    '复位按钮-设置': {'Name': '复位按钮-设置', 'DataType': 'bool', 'Address': 'DB5033.DBX22.5'},
    '急停按钮-设置': {'Name': '急停按钮-设置', 'DataType': 'bool', 'Address': 'DB5033.DBX22.6'},
    '备用-设置': {'Name': '备用-设置', 'DataType': 'bool', 'Address': 'DB5033.DBX22.7'}}
