# left:reya 1-4, right: reya 5-8
robot_left_sites = {
    '模具腔数': {'Name': '模具腔数', 'DataType': 'Int', 'Address': 'DB511.DBW0'},
    '工作位': {'Name': '工作位', 'DataType': 'Int', 'Address': 'DB511.DBW2'},
    '主料X1': {'Name': '主料X1', 'DataType': 'Real', 'Address': 'DB511.DBD4'},
    '主料Y1': {'Name': '主料Y1', 'DataType': 'Real', 'Address': 'DB511.DBD8'},
    '主料X2': {'Name': '主料X2', 'DataType': 'Real', 'Address': 'DB511.DBD12'},
    '主料Y2': {'Name': '主料Y2', 'DataType': 'Real', 'Address': 'DB511.DBD16'},
    '主料X3': {'Name': '主料X3', 'DataType': 'Real', 'Address': 'DB511.DBD20'},
    '主料Y3': {'Name': '主料Y3', 'DataType': 'Real', 'Address': 'DB511.DBD24'},
    '主料X4': {'Name': '主料X4', 'DataType': 'Real', 'Address': 'DB511.DBD28'},
    '主料Y4': {'Name': '主料Y4', 'DataType': 'Real', 'Address': 'DB511.DBD32'},
    '主料X5': {'Name': '主料X5', 'DataType': 'Real', 'Address': 'DB511.DBD36'},
    '主料Y5': {'Name': '主料Y5', 'DataType': 'Real', 'Address': 'DB511.DBD40'},
    '主料X6': {'Name': '主料X6', 'DataType': 'Real', 'Address': 'DB511.DBD44'},
    '主料Y6': {'Name': '主料Y6', 'DataType': 'Real', 'Address': 'DB511.DBD48'},
    '辅料X1': {'Name': '辅料X1', 'DataType': 'Real', 'Address': 'DB511.DBD52'},
    '辅料Y1': {'Name': '辅料Y1', 'DataType': 'Real', 'Address': 'DB511.DBD56'},
    '辅料X2': {'Name': '辅料X2', 'DataType': 'Real', 'Address': 'DB511.DBD60'},
    '辅料Y2': {'Name': '辅料Y2', 'DataType': 'Real', 'Address': 'DB511.DBD64'},
    '辅料X3': {'Name': '辅料X3', 'DataType': 'Real', 'Address': 'DB511.DBD68'},
    '辅料Y3': {'Name': '辅料Y3', 'DataType': 'Real', 'Address': 'DB511.DBD72'},
    '辅料X4': {'Name': '辅料X4', 'DataType': 'Real', 'Address': 'DB511.DBD76'},
    '辅料Y4': {'Name': '辅料Y4', 'DataType': 'Real', 'Address': 'DB511.DBD80'},
    '辅料X5': {'Name': '辅料X5', 'DataType': 'Real', 'Address': 'DB511.DBD84'},
    '辅料Y5': {'Name': '辅料Y5', 'DataType': 'Real', 'Address': 'DB511.DBD88'},
    '主料摊平速度': {'Name': '主料摊平速度', 'DataType': 'Real', 'Address': 'DB511.DBD92'},
    '辅料摊平速度': {'Name': '辅料摊平速度', 'DataType': 'Real', 'Address': 'DB511.DBD96'},
    '中模清扫偏移': {'Name': '中模清扫偏移', 'DataType': 'Real', 'Address': 'DB511.DBD100'},
    '上模清扫偏移': {'Name': '上模清扫偏移', 'DataType': 'Real', 'Address': 'DB511.DBD104'},
    '加料位置偏移': {'Name': '加料位置偏移', 'DataType': 'Real', 'Address': 'DB511.DBD108'},
    'Middle_Y2': {'Name': 'Middle_Y2', 'DataType': 'Real', 'Address': 'DB511.DBD112'},
    'Up_Y2': {'Name': 'Up_Y2', 'DataType': 'Real', 'Address': 'DB511.DBD116'},
    'H2': {'Name': 'H2', 'DataType': 'Real', 'Address': 'DB511.DBD120'},
    'Middle_Y3': {'Name': 'Middle_Y3', 'DataType': 'Real', 'Address': 'DB511.DBD124'},
    'Up_Y3': {'Name': 'Up_Y3', 'DataType': 'Real', 'Address': 'DB511.DBD128'},
    'H3': {'Name': 'H3', 'DataType': 'Real', 'Address': 'DB511.DBD132'},
    'Middle_Y4': {'Name': 'Middle_Y4', 'DataType': 'Real', 'Address': 'DB511.DBD136'},
    'Up_Y4': {'Name': 'Up_Y4', 'DataType': 'Real', 'Address': 'DB511.DBD140'},
    'H4': {'Name': 'H4', 'DataType': 'Real', 'Address': 'DB511.DBD144'},
    'order': {'Name': 'order', 'DataType': 'Int', 'Address': 'DB511.DBW148'},
    '模具类型': {'Name': '模具类型', 'DataType': 'Real', 'Address': 'DB511.DBD150'},
    '启动': {'Name': '启动', 'DataType': 'Int', 'Address': 'DB511.DBW268'},
    '申请参数': {'Name': '申请参数', 'DataType': 'Int', 'Address': 'DB511.DBW270'},
    'spare44': {'Name': 'spare44', 'DataType': 'Int', 'Address': 'DB511.DBW272'}}

robot_right_sites = {
    '模具腔数': {'Name': '模具腔数', 'DataType': 'Int', 'Address': 'DB511.DBW274'},
    '工作位': {'Name': '工作位', 'DataType': 'Int', 'Address': 'DB511.DBW276'},
    '主料X1': {'Name': '主料X1', 'DataType': 'Real', 'Address': 'DB511.DBD278'},
    '主料Y1': {'Name': '主料Y1', 'DataType': 'Real', 'Address': 'DB511.DBD282'},
    '主料X2': {'Name': '主料X2', 'DataType': 'Real', 'Address': 'DB511.DBD286'},
    '主料Y2': {'Name': '主料Y2', 'DataType': 'Real', 'Address': 'DB511.DBD290'},
    '主料X3': {'Name': '主料X3', 'DataType': 'Real', 'Address': 'DB511.DBD294'},
    '主料Y3': {'Name': '主料Y3', 'DataType': 'Real', 'Address': 'DB511.DBD298'},
    '主料X4': {'Name': '主料X4', 'DataType': 'Real', 'Address': 'DB511.DBD302'},
    '主料Y4': {'Name': '主料Y4', 'DataType': 'Real', 'Address': 'DB511.DBD306'},
    '主料X5': {'Name': '主料X5', 'DataType': 'Real', 'Address': 'DB511.DBD310'},
    '主料Y5': {'Name': '主料Y5', 'DataType': 'Real', 'Address': 'DB511.DBD314'},
    '主料X6': {'Name': '主料X6', 'DataType': 'Real', 'Address': 'DB511.DBD318'},
    '主料Y6': {'Name': '主料Y6', 'DataType': 'Real', 'Address': 'DB511.DBD322'},
    '辅料X1': {'Name': '辅料X1', 'DataType': 'Real', 'Address': 'DB511.DBD326'},
    '辅料Y1': {'Name': '辅料Y1', 'DataType': 'Real', 'Address': 'DB511.DBD330'},
    '辅料X2': {'Name': '辅料X2', 'DataType': 'Real', 'Address': 'DB511.DBD334'},
    '辅料Y2': {'Name': '辅料Y2', 'DataType': 'Real', 'Address': 'DB511.DBD338'},
    '辅料X3': {'Name': '辅料X3', 'DataType': 'Real', 'Address': 'DB511.DBD342'},
    '辅料Y3': {'Name': '辅料Y3', 'DataType': 'Real', 'Address': 'DB511.DBD346'},
    '辅料X4': {'Name': '辅料X4', 'DataType': 'Real', 'Address': 'DB511.DBD350'},
    '辅料Y4': {'Name': '辅料Y4', 'DataType': 'Real', 'Address': 'DB511.DBD354'},
    '辅料X5': {'Name': '辅料X5', 'DataType': 'Real', 'Address': 'DB511.DBD358'},
    '辅料Y5': {'Name': '辅料Y5', 'DataType': 'Real', 'Address': 'DB511.DBD362'},
    '主料摊平速度': {'Name': '主料摊平速度', 'DataType': 'Real', 'Address': 'DB511.DBD366'},
    '辅料摊平速度': {'Name': '辅料摊平速度', 'DataType': 'Real', 'Address': 'DB511.DBD370'},
    '中模清扫偏移': {'Name': '中模清扫偏移', 'DataType': 'Real', 'Address': 'DB511.DBD374'},
    '上模清扫偏移': {'Name': '上模清扫偏移', 'DataType': 'Real', 'Address': 'DB511.DBD378'},
    '加料位置偏移': {'Name': '加料位置偏移', 'DataType': 'Real', 'Address': 'DB511.DBD382'},
    'Middle_Y2': {'Name': 'Middle_Y2', 'DataType': 'Real', 'Address': 'DB511.DBD386'},
    'Up_Y2': {'Name': 'Up_Y2', 'DataType': 'Real', 'Address': 'DB511.DBD390'},
    'H2': {'Name': 'H2', 'DataType': 'Real', 'Address': 'DB511.DBD394'},
    'Middle_Y3': {'Name': 'Middle_Y3', 'DataType': 'Real', 'Address': 'DB511.DBD398'},
    'Up_Y3': {'Name': 'Up_Y3', 'DataType': 'Real', 'Address': 'DB511.DBD402'},
    'H3': {'Name': 'H3', 'DataType': 'Real', 'Address': 'DB511.DBD406'},
    'Middle_Y4': {'Name': 'Middle_Y4', 'DataType': 'Real', 'Address': 'DB511.DBD410'},
    'Up_Y4': {'Name': 'Up_Y4', 'DataType': 'Real', 'Address': 'DB511.DBD414'},
    'H4': {'Name': 'H4', 'DataType': 'Real', 'Address': 'DB511.DBD418'},
    'order': {'Name': 'order', 'DataType': 'Int', 'Address': 'DB511.DBW422'},
    '模具类型': {'Name': '模具类型', 'DataType': 'Real', 'Address': 'DB511.DBD424'},
    '启动': {'Name': '启动', 'DataType': 'Int', 'Address': 'DB511.DBW542'},
    '申请参数': {'Name': '申请参数', 'DataType': 'Int', 'Address': 'DB511.DBW544'},
    'spare44': {'Name': 'spare44', 'DataType': 'Int', 'Address': 'DB511.DBW546'}}

robot_left_status_read_sites = {
    '启动状态-实时': {'Name': '启动状态-实时', 'DataType': 'bool', 'Address': 'DB500.DBX0.0'},
    '自动状态-实时': {'Name': '自动状态-实时', 'DataType': 'bool', 'Address': 'DB500.DBX0.1'},
    '半自动状态-实时': {'Name': '半自动状态-实时', 'DataType': 'bool', 'Address': 'DB500.DBX0.2'},
    '手动状态-实时': {'Name': '手动状态-实时', 'DataType': 'bool', 'Address': 'DB500.DBX0.3'},
    '复位状态-实时': {'Name': '复位状态-实时', 'DataType': 'bool', 'Address': 'DB500.DBX0.4'},
    '急停状态-实时': {'Name': '急停状态-实时', 'DataType': 'bool', 'Address': 'DB500.DBX0.6'},
    '备用-实时': {'Name': '备用-实时', 'DataType': 'bool', 'Address': 'DB500.DBX0.7'}}

robot_right_status_read_sites = {
    '启动状态-实时': {'Name': '启动状态-实时', 'DataType': 'bool', 'Address': 'DB501.DBX116.0'},
    '自动状态-实时': {'Name': '自动状态-实时', 'DataType': 'bool', 'Address': 'DB500.DBX274.1'},
    '半自动状态-实时': {'Name': '半自动状态-实时', 'DataType': 'bool', 'Address': 'DB500.DBX274.2'},
    '手动状态-实时': {'Name': '手动状态-实时', 'DataType': 'bool', 'Address': 'DB500.DBX274.3'},
    '复位状态-实时': {'Name': '复位状态-实时', 'DataType': 'bool', 'Address': 'DB500.DBX274.4'},
    '急停状态-实时': {'Name': '急停状态-实时', 'DataType': 'bool', 'Address': 'DB500.DBX274.6'},
    # '备用-实时': {'Name': '备用-实时', 'DataType': 'bool', 'Address': 'DB5033.DBX22.7'}
}

robot_status_write_left_sites = {
    '弃料按钮-设置': {'Name': '弃料按钮-设置', 'DataType': 'bool', 'Address': 'DB503.DBX22.0'},
    '手动按钮-设置': {'Name': '手动按钮-设置', 'DataType': 'bool', 'Address': 'DB503.DBX22.1'},
    '自动按钮-设置': {'Name': '自动按钮-设置', 'DataType': 'bool', 'Address': 'DB503.DBX22.2'},
    '半自动按钮-设置': {'Name': '半自动按钮-设置', 'DataType': 'bool', 'Address': 'DB503.DBX22.3'},
    '启动按钮-设置': {'Name': '启动按钮-设置', 'DataType': 'bool', 'Address': 'DB503.DBX22.4'},
    '复位按钮-设置': {'Name': '复位按钮-设置', 'DataType': 'bool', 'Address': 'DB503.DBX22.5'},
    '急停按钮-设置': {'Name': '急停按钮-设置', 'DataType': 'bool', 'Address': 'DB503.DBX22.6'},
    '备用-设置': {'Name': '备用-设置', 'DataType': 'bool', 'Address': 'DB503.DBX22.7'}}

robot_status_write_right_sites = {
    '弃料按钮-设置': {'Name': '弃料按钮-设置', 'DataType': 'bool', 'Address': 'DB5033.DBX22.0'},
    '手动按钮-设置': {'Name': '手动按钮-设置', 'DataType': 'bool', 'Address': 'DB5033.DBX22.1'},
    '自动按钮-设置': {'Name': '自动按钮-设置', 'DataType': 'bool', 'Address': 'DB5033.DBX22.2'},
    '半自动按钮-设置': {'Name': '半自动按钮-设置', 'DataType': 'bool', 'Address': 'DB5033.DBX22.3'},
    '启动按钮-设置': {'Name': '启动按钮-设置', 'DataType': 'bool', 'Address': 'DB5033.DBX22.4'},
    '复位按钮-设置': {'Name': '复位按钮-设置', 'DataType': 'bool', 'Address': 'DB5033.DBX22.5'},
    '急停按钮-设置': {'Name': '急停按钮-设置', 'DataType': 'bool', 'Address': 'DB5033.DBX22.6'},
    '备用-设置': {'Name': '备用-设置', 'DataType': 'bool', 'Address': 'DB5033.DBX22.7'}}
